### ISSUE TITLE
[Bug] [General] [💥] Missing Microsoft.Web.WebView2.* Dependencies in Installer Bundle; App Crash on Startup

### ISSUE THREAD

**Issue by dovry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#420]
1.6.0 Worked fine yesterday, as I reported this #416 
I wanted to bughunt some more, but I encountered this error, even after nuking my settings.

![image](https://user-images.githubusercontent.com/15201298/185066706-95716085-161e-4492-aa3e-1ae5b6d28e6c.png)

```
---------------------------
Unexpected Error Occurred: Dispatcher.UnhandledException
---------------------------
The following exception occurred:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Web.WebView2.WinForms, Version=1.0.1293.44, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' or one of its dependencies. The system cannot find the file specified.

File name: 'Microsoft.Web.WebView2.WinForms, Version=1.0.1293.44, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Web.WebView2.WinForms, Version=1.0.1264.42, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' or one of its dependencies. The system cannot find the file specified.

File name: 'Microsoft.Web.WebView2.WinForms, Version=1.0.1264.42, Culture=neutral, PublicKeyToken=2a8ab48044d2601e'



WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



   at void AutoUpdaterDotNET.UpdateForm.InitializeComponent()

   at new AutoUpdaterDotNET.UpdateForm(UpdateInfoEventArgs args)

   at void AutoUpdaterDotNET.AutoUpdater.ShowUpdateForm(UpdateInfoEventArgs args)

   at bool AutoUpdaterDotNET.AutoUpdater.StartUpdate(object result)

   at void AutoUpdaterDotNET.AutoUpdater.Start(string appCast, Assembly myAssembly)+(object _, RunWorkerCompletedEventArgs args) => { }

   at void System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

   at void System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(object arg)

   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)

   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)






Please report this issue on GitHub or in our Discord :^)

Sometimes, NUKING 💣💥🧨 your settings can help resolve certain issues.

Press 'YES' if you want to try deleting your settings to fix your issue, and the app will restart automatically with the default settings loaded.
---------------------------
Yes   No   
---------------------------

```

**Comment by HiMarioLopez** [comment]
Fix has been deployed, download link to the new installer should be the same as the last

https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/1.6.0

Can you confirm this one works?

**Comment by dovry** [comment]
after updating to the release you linked, I get this on every restart, even after running the update. 
`remind me later` works, though.

![image](https://user-images.githubusercontent.com/15201298/185150451-11bf44bf-7ce7-4985-8ac5-93e8633a324b.png)


and resizing the UI still doesn't redraw the UI #416 
![ChaosRecipeEnhancer_DIafzot4FU](https://user-images.githubusercontent.com/15201298/185151481-ba2db157-0242-4fba-9c05-de7b8e87fac4.gif)

**Comment by HiMarioLopez** [comment]
Checking on these 2 things now!

**Comment by HiMarioLopez** [comment]
Looks like you're running an older version of the app (1.6.0 =/= 1.6.0.0, because i'm terrible), can you go into your program manager, uninstall previous version of the app, and reinstall using that same link? 

I put out the updated installer just this morning. Let me know if that fixes these 2 things

Apologies for the confusion! @dovry

**Comment by dovry** [comment]
![image](https://user-images.githubusercontent.com/15201298/185155974-fe76733b-2374-4e27-84da-0638c44d5861.png)
this is before uninstalling lol

uninstalling fixed the update and #416 issue.

I'm not sure what caused the webview problem, though.

**Comment by HiMarioLopez** [comment]
Fixed in v1.6.0

https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/1.6.0

Thanks for your issue report! Enjoy the league
